# Generated by Django 3.2.6 on 2021-09-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="comment",
            new_name="comment_text",
        ),
    ]
