# Generated by Django 3.2.6 on 2021-10-01 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_post_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_post', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file_type',
            field=models.CharField(choices=[(1, 'Ebook'), (2, 'Video'), (3, 'Music'), (4, 'Image'), (5, 'Other')], default='other', max_length=10),
        ),
    ]
